export {default as Header} from './header/Header'
export {default as Home} from './home/Home'
export {default as ListSearchMovies} from './listSearchMovies/ListSearchMovies'
export {default as Router} from './router/Router'
export {default as DetailMovie} from './detailMovie/DetailMovie'
export {default as SearchSelect} from './header/searchBar/SearchSelect'